/**
 * GENERATED by scripts/gen-routes.mjs — do not edit by hand.
 *
 * Every public route in the App Router, with the newest mtime beneath it so the
 * sitemap can set a truthful lastModified. Run `pnpm gen:routes` after adding,
 * renaming or deleting a page; `pnpm build` does it for you.
 *
 * 70 routes.
 */
export interface RouteEntry {
  path: string;
  /** ISO date of the newest file under the route directory. */
  mtime: string;
}

export const routes: RouteEntry[] = [
  {
    "path": "/",
    "mtime": "2026-10-03T23:59:00.873Z"
  },
  {
    "path": "/assurance-loyer-impaye",
    "mtime": "2026-10-03T23:36:29.121Z"
  },
  {
    "path": "/bail",
    "mtime": "2026-10-03T23:36:29.110Z"
  },
  {
    "path": "/blog",
    "mtime": "2026-10-03T23:19:27.397Z"
  },
  {
    "path": "/cgu",
    "mtime": "2026-10-03T23:19:27.398Z"
  },
  {
    "path": "/comparatif",
    "mtime": "2026-10-03T23:36:29.118Z"
  },
  {
    "path": "/comparatif/assurance-loyer-impaye",
    "mtime": "2026-10-03T23:36:29.118Z"
  },
  {
    "path": "/comparatif/bail-electronique-vs-papier",
    "mtime": "2026-10-03T23:36:29.117Z"
  },
  {
    "path": "/comparatif/logiciel-gestion-locative",
    "mtime": "2026-10-03T23:36:29.118Z"
  },
  {
    "path": "/comparatif/quittance-de-loyer-vs-attestation",
    "mtime": "2026-10-03T23:36:29.117Z"
  },
  {
    "path": "/comparatif/rentready-vs-gerclegeo",
    "mtime": "2026-10-03T23:36:29.118Z"
  },
  {
    "path": "/comparatif/rentready-vs-immotop",
    "mtime": "2026-10-03T23:36:29.117Z"
  },
  {
    "path": "/comparatif/rentready-vs-legalplace",
    "mtime": "2026-10-03T23:36:29.118Z"
  },
  {
    "path": "/demo",
    "mtime": "2026-10-03T23:19:27.398Z"
  },
  {
    "path": "/entretien",
    "mtime": "2026-10-03T23:19:27.398Z"
  },
  {
    "path": "/features",
    "mtime": "2026-10-03T23:23:13.023Z"
  },
  {
    "path": "/gestion-locative",
    "mtime": "2026-10-03T23:36:29.117Z"
  },
  {
    "path": "/glossaire-immobilier",
    "mtime": "2026-10-03T23:36:29.122Z"
  },
  {
    "path": "/guides",
    "mtime": "2026-10-03T13:07:27.415Z"
  },
  {
    "path": "/guides/depot-garantie",
    "mtime": "2026-10-03T13:07:27.399Z"
  },
  {
    "path": "/guides/irl-2026",
    "mtime": "2026-10-03T13:07:27.415Z"
  },
  {
    "path": "/guides/modele-bail",
    "mtime": "2026-10-03T13:07:27.404Z"
  },
  {
    "path": "/guides/quittance-loyer",
    "mtime": "2026-10-03T13:07:27.409Z"
  },
  {
    "path": "/guides/relance-loyer",
    "mtime": "2026-10-03T13:07:27.392Z"
  },
  {
    "path": "/locations",
    "mtime": "2026-10-03T23:36:29.120Z"
  },
  {
    "path": "/mentions-legales",
    "mtime": "2026-10-03T23:19:27.399Z"
  },
  {
    "path": "/outils",
    "mtime": "2026-10-03T23:43:23.064Z"
  },
  {
    "path": "/outils/calculateur-charges-locatives",
    "mtime": "2026-10-03T23:36:29.112Z"
  },
  {
    "path": "/outils/calculateur-depot-garantie",
    "mtime": "2026-10-03T23:40:58.111Z"
  },
  {
    "path": "/outils/calculateur-irl",
    "mtime": "2026-10-03T23:34:43.830Z"
  },
  {
    "path": "/outils/calculateur-loyer",
    "mtime": "2026-10-03T23:36:29.112Z"
  },
  {
    "path": "/outils/calculateur-plus-value",
    "mtime": "2026-10-03T23:36:29.115Z"
  },
  {
    "path": "/outils/calculateur-preavis",
    "mtime": "2026-10-03T23:36:29.115Z"
  },
  {
    "path": "/outils/calculateur-rendement",
    "mtime": "2026-10-03T23:43:23.064Z"
  },
  {
    "path": "/outils/calculateur-surface-habitable",
    "mtime": "2026-10-03T23:36:29.111Z"
  },
  {
    "path": "/outils/checklist-etat-lieux",
    "mtime": "2026-10-03T23:36:29.114Z"
  },
  {
    "path": "/outils/generateur-conge-vente",
    "mtime": "2026-10-03T23:36:29.114Z"
  },
  {
    "path": "/outils/generateur-quittance",
    "mtime": "2026-10-03T23:34:43.831Z"
  },
  {
    "path": "/outils/lettre-relance-loyer",
    "mtime": "2026-10-03T23:36:29.116Z"
  },
  {
    "path": "/outils/modele-quittance-loyer-pdf",
    "mtime": "2026-10-01T18:47:13.577Z"
  },
  {
    "path": "/outils/simulateur-fiscalite-lmnp",
    "mtime": "2026-10-03T23:36:29.111Z"
  },
  {
    "path": "/outils/simulateur-loi-jeanbrun",
    "mtime": "2026-10-03T22:43:16.439Z"
  },
  {
    "path": "/outils/simulateur-pret-immobilier",
    "mtime": "2026-10-03T23:36:29.114Z"
  },
  {
    "path": "/politique-confidentialite",
    "mtime": "2026-10-03T23:19:27.400Z"
  },
  {
    "path": "/politique-cookies",
    "mtime": "2026-10-03T23:19:27.400Z"
  },
  {
    "path": "/pricing",
    "mtime": "2026-10-03T23:23:13.022Z"
  },
  {
    "path": "/quittances",
    "mtime": "2026-10-03T23:36:29.108Z"
  },
  {
    "path": "/templates",
    "mtime": "2026-10-03T13:07:27.426Z"
  },
  {
    "path": "/templates/augmentation-de-loyer",
    "mtime": "2026-10-02T06:03:45.087Z"
  },
  {
    "path": "/templates/bail-colocation",
    "mtime": "2026-10-01T20:50:30.689Z"
  },
  {
    "path": "/templates/bail-commercial",
    "mtime": "2026-10-03T22:54:24.364Z"
  },
  {
    "path": "/templates/bail-meuble",
    "mtime": "2026-10-03T23:19:27.401Z"
  },
  {
    "path": "/templates/bail-mobilite",
    "mtime": "2026-10-03T22:54:24.367Z"
  },
  {
    "path": "/templates/bail-professionnel",
    "mtime": "2026-10-01T20:50:30.689Z"
  },
  {
    "path": "/templates/bail-vide",
    "mtime": "2026-10-03T23:19:27.401Z"
  },
  {
    "path": "/templates/conge-locataire",
    "mtime": "2026-10-03T22:54:24.367Z"
  },
  {
    "path": "/templates/conge-proprietaire",
    "mtime": "2026-10-03T22:54:24.364Z"
  },
  {
    "path": "/templates/contrat-de-location",
    "mtime": "2026-10-03T13:28:05.650Z"
  },
  {
    "path": "/templates/etat-des-lieux",
    "mtime": "2026-10-03T22:54:24.366Z"
  },
  {
    "path": "/templates/lease",
    "mtime": "2026-10-03T22:54:24.366Z"
  },
  {
    "path": "/templates/lease/acte-caution",
    "mtime": "2026-10-03T22:54:24.365Z"
  },
  {
    "path": "/templates/lease/bail-etudiant",
    "mtime": "2026-10-03T22:54:24.365Z"
  },
  {
    "path": "/templates/lease/bail-parking",
    "mtime": "2026-10-03T22:54:24.365Z"
  },
  {
    "path": "/templates/lease/bail-precaire",
    "mtime": "2026-10-03T22:54:24.365Z"
  },
  {
    "path": "/templates/lease/bail-saisonnier",
    "mtime": "2026-10-03T22:54:24.366Z"
  },
  {
    "path": "/templates/protocol-etat-des-lieux",
    "mtime": "2026-10-01T20:50:30.690Z"
  },
  {
    "path": "/templates/recu-loyer",
    "mtime": "2026-10-01T18:47:13.576Z"
  },
  {
    "path": "/templates/relance-loyer-impaye",
    "mtime": "2026-10-01T20:50:30.689Z"
  },
  {
    "path": "/templates/repartition-charges",
    "mtime": "2026-10-03T13:28:05.650Z"
  },
  {
    "path": "/villes",
    "mtime": "2026-10-03T23:36:29.110Z"
  }
];
